create table if not exists court (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    sport_type varchar(50) not null,
    indoor boolean not null,
    heated boolean not null,
    lighting boolean not null,
    surface varchar(255),
    notes varchar(1000),
    price_per_hour numeric(10,2) not null,
    open_time time not null,
    close_time time not null,
    active boolean not null
);

create table if not exists booking (
    id bigint generated by default as identity primary key,
    court_id bigint not null references court(id),
    booking_date date not null,
    start_time time not null,
    end_time time not null,
    customer_name varchar(255) not null,
    customer_phone varchar(255) not null,
    customer_email varchar(255),
    status varchar(50) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    price numeric(10,2) not null
);

create index if not exists idx_booking_court_date on booking(court_id, booking_date);

