CREATE TABLE subscription_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id INT NOT NULL,
    sport_type VARCHAR(50) NOT NULL,
    subscription_type VARCHAR(50) NOT NULL,
    preferred_schedule TEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sub_player FOREIGN KEY (player_id) REFERENCES player_users(id)
);
