-- Fix ID type mismatch between Java (Long) and Database (Integer)
-- Dropping constraints
ALTER TABLE booking DROP CONSTRAINT IF EXISTS fk_booking_player_user;
ALTER TABLE subscription_requests DROP CONSTRAINT IF EXISTS fk_sub_player;

-- H2/Postgres compatible BIGINT conversion with Identity preservation
ALTER TABLE player_users ALTER COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE booking ALTER COLUMN player_user_id BIGINT;
ALTER TABLE subscription_requests ALTER COLUMN player_id BIGINT;

-- Re-adding constraints
ALTER TABLE booking ADD CONSTRAINT fk_booking_player_user FOREIGN KEY (player_user_id) REFERENCES player_users(id);
ALTER TABLE subscription_requests ADD CONSTRAINT fk_sub_player FOREIGN KEY (player_id) REFERENCES player_users(id);
