ALTER TABLE booking
ADD COLUMN payment_method VARCHAR(255) NOT NULL DEFAULT 'CASH';

ALTER TABLE booking
ADD COLUMN payment_status VARCHAR(255) NOT NULL DEFAULT 'PENDING';

ALTER TABLE booking
ADD COLUMN transaction_id VARCHAR(255);
