-- V47: Open Match (matchmaking) + nivel de joc per jucator.
-- Strict aditiv: doar tabele noi. Nu modifica booking, court sau player_users.

-- Nivelul de joc al unui jucator, per sport (Faza 1: PADEL).
-- level_rank: 0=Hobby, 1=Incepator, 2=M4, 3=M3, 4=M2, 5=M1
CREATE TABLE player_skill_level (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_user_id  BIGINT       NOT NULL,
    sport_type      VARCHAR(32)  NOT NULL,
    level_rank      INT          NOT NULL,
    updated_at      TIMESTAMP    NOT NULL,
    CONSTRAINT uq_psl_player_sport UNIQUE (player_user_id, sport_type),
    CONSTRAINT fk_psl_player FOREIGN KEY (player_user_id) REFERENCES player_users(id),
    CONSTRAINT ck_psl_rank CHECK (level_rank BETWEEN 0 AND 5)
);

-- O partida deschisa: legata 1:1 de o rezervare existenta (booking).
-- group_size = cati jucatori are deja organizatorul (inclusiv el): 2 sau 3.
-- total_slots = 4 la padel. status: OPEN / FULL / CANCELLED.
-- release_at = momentul la care partida neumpluta se anuleaza automat si
--              terenul se elibereaza (de regula start - 6 ore).
CREATE TABLE open_match (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id           BIGINT       NOT NULL,
    organizer_player_id  BIGINT       NOT NULL,
    sport_type           VARCHAR(32)  NOT NULL,
    target_level_rank    INT          NOT NULL,
    group_size           INT          NOT NULL,
    total_slots          INT          NOT NULL,
    status               VARCHAR(16)  NOT NULL,
    release_at           TIMESTAMP    NOT NULL,
    created_at           TIMESTAMP    NOT NULL,
    updated_at           TIMESTAMP    NOT NULL,
    CONSTRAINT uq_om_booking UNIQUE (booking_id),
    CONSTRAINT fk_om_booking FOREIGN KEY (booking_id) REFERENCES booking(id),
    CONSTRAINT fk_om_organizer FOREIGN KEY (organizer_player_id) REFERENCES player_users(id),
    CONSTRAINT ck_om_group CHECK (group_size BETWEEN 1 AND 4),
    CONSTRAINT ck_om_rank CHECK (target_level_rank BETWEEN 0 AND 5)
);

-- Jucatorii care s-au alaturat unei partide deschise (fara organizator).
-- Constrangerea unica impiedica alaturarea dubla a aceluiasi jucator.
CREATE TABLE open_match_participant (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    open_match_id   BIGINT    NOT NULL,
    player_user_id  BIGINT    NOT NULL,
    joined_at       TIMESTAMP NOT NULL,
    CONSTRAINT uq_omp_match_player UNIQUE (open_match_id, player_user_id),
    CONSTRAINT fk_omp_match FOREIGN KEY (open_match_id) REFERENCES open_match(id),
    CONSTRAINT fk_omp_player FOREIGN KEY (player_user_id) REFERENCES player_users(id)
);

CREATE INDEX idx_om_status ON open_match(status);
CREATE INDEX idx_omp_match ON open_match_participant(open_match_id);
